name: gym_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.4
  confetti: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
